version: '3.8'

services:
  medical-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medicaldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
